name: keybinder
description: >-
  A utility class used to bind callbacks to a combination
  of zero or more physical keys on a keyboard.
version: 1.0.1
homepage: https://github.com/james-alex/keybinder

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  list_utilities: ^1.0.1
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
